exclude: '(^foodsave-frontend/node_modules/|foodsave-frontend/.next/)'
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args: [--profile=black]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: [--config=pyproject.toml]
        exclude: ^(docs/|examples/|scripts/|tests/|venv/|node_modules/|typings/|.vscode/|.idea/|.git/|.mypy_cache/|.pytest_cache/|build/|dist/|htmlcov/)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml]
        exclude: ^(docs/|examples/|scripts/|tests/|venv/|node_modules/|typings/|.vscode/|.idea/|.git/|.mypy_cache/|.pytest_cache/|build/|dist/|htmlcov/)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
