services:
  # Loki - Log aggregation system
  loki:
    image: grafana/loki:2.9.6
    container_name: foodsave-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - ./monitoring/loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      foodsave-monitoring:
        ipv4_address: 172.21.0.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Promtail - Log collector
  promtail:
    image: grafana/promtail:2.9.6
    container_name: foodsave-promtail
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./logs:/logs:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - foodsave-monitoring
    depends_on:
      - loki
    restart: unless-stopped

  # Grafana - Visualization platform
  grafana:
    image: grafana/grafana:10.4.0
    container_name: foodsave-grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=foodsave
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./monitoring/grafana-data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - foodsave-monitoring
    depends_on:
      - loki
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  loki_data:
    driver: local
  grafana_data:
    driver: local

networks:
  foodsave-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16 