server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.20.0.10:3100/loki/api/v1/push

scrape_configs:
  # Docker container discovery for all containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
      - output:
          source: message

  # Keep existing file-based log collection for specific services
  - job_name: foodsave-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: foodsave-backend
          app: backend
          __path__: /logs/backend/*log

  - job_name: foodsave-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: foodsave-frontend
          app: frontend
          __path__: /logs/frontend/*log

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /logs/nginx/*log

  - job_name: ollama
    static_configs:
      - targets:
          - localhost
        labels:
          job: ollama
          __path__: /logs/ollama/*log

  - job_name: redis_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /logs/redis/*log

  - job_name: postgres_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: /logs/postgres/*log
