"""rename metadata to doc_metadata in rag_documents

Revision ID: e7c7d000c8d2
Revises: 8ceb8a5f471d
Create Date: 2025-06-26 16:44:00.925783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c7d000c8d2'
down_revision: Union[str, Sequence[str], None] = '8ceb8a5f471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
