apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki_foodsave_logs
    access: proxy
    url: http://foodsave-loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: loki_foodsave_logs
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
