apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_foodsave_metrics
    access: proxy
    url: http://foodsave-prometheus-dev:9090
    isDefault: false
    editable: true
