  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pre-commit run --all-files
      - run: poetry run pytest --cov=backend --cov-report=xml
      - uses: codecov/codecov-action@v3
      - run: poetry run bandit -r backend
      - run: poetry run safety check
